"""
This program will process the output data generated by executer.py
to a gnuplot readable text file.

@argv[1]: the output file to be processed
@argv[2]: graph's prefix

@Auth: FATESAIKOU
"""

import json
import sys


def process(data):
    for col in data.keys():
        data[col].sort(lambda a, b: a[1] - b[1])
        data[col].sort(lambda a, b: a[0] - b[0] if a[1] == b[1] else 0)

    return data


def writePlotData(result, prefix):
    data = result['data']

    for col in data.keys():
        records = data[col]

        s = ""
        pre_val = -1
        for i in xrange(len(records)):
            if i != 0 and pre_val != records[i][1]:
                s += '\n'

            s += str(records[i][2]) + '\n'
            pre_val = records[i][1]

        src = open(prefix + '-' + col + '.txt', 'w')
        src.write(s)
        src.close()


    db_description = result['db']
    s = ""
    for (k, v) in db_description:
        s += str(k) + ' ' + str(v) + '\n'
        
    src = open(prefix + '-db.txt', 'w')
    src.write(s)
    src.close()


def main():
    result_file = sys.argv[1]
    output_file_prefix = sys.argv[2]

    src = open(result_file, 'r')
    result = json.loads(src.read())
    src.close()

    result['data'] = process(result['data'])
    writePlotData(result, output_file_prefix)
    

if __name__ == "__main__":
    main()
