"""
This program will process the output data generated by executer.py
to a gnuplot readable text file.

@argv[1]: the output file to be processed
@argv[2]: graph's prefix

@Auth: FATESAIKOU
"""

import json
import sys


def process(data):
    for col in data.keys():
        data[col].sort(lambda a, b: a[1] - b[1])
        data[col].sort(lambda a, b: a[0] - b[0] if a[1] == b[1] else 0)

    return data


def writePlotData(data, prefix):
    for col in data.keys():
        records = data[col]

        s = ""
        pre_val = -1
        for i in xrange(len(records)):
            if i != 0 and pre_val != records[i][1]:
                s += '\n'

            s += str(records[i][2]) + '\n'
            pre_val = records[i][1]

        src = open(prefix + '-' + col + '.txt', 'w')
        src.write(s)
        src.close()


def main():
    data_file = sys.argv[1]
    output_file_prefix = sys.argv[2]

    src = open(data_file, 'r')
    data = json.loads(src.read())
    src.close()

    n_data = process(data)
    writePlotData(n_data, output_file_prefix)
    

if __name__ == "__main__":
    main()
